### ISSUE TITLE
Detected code that calls async_forward_entry_setup without awaiting async_forward_entry_setup. This will stop working in Home Assistant 2025.1.

### ISSUE THREAD

**Issue by danielbrunt57** [parvez/network_scanner#11]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:151
First occurred: 1:02:44 AM (1 occurrences)
Last logged: 1:02:44 AM

Detected code that calls async_forward_entry_setup for integration network_scanner with title: Network Scanner and entry_id: 6e0451e0373edf729796de358888d8e6, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by parvez** [comment]
thanks for the fix! merged! please help verity
