### ISSUE TITLE
How to edit configuration?

### ISSUE THREAD

**Issue by yff77** [parvez/network_scanner#3]
Perhaps a silly question: is there any way to edit the configuration (e.g. add more lines with custom data for MAC addresses)? Or has the integration to be added as a new one each time with all the custom data?

**Comment by parvez** [comment]
With recent addition of Hostname and Vendor information from `nmap` itself, I am thinking of getting rid of custom data in future. Currently editing is not possible. I usually remove and add it again. It helps if you add the mac mapping list in configuration.yaml, and it will populate the mac settings in the modal when you add it again.

<img width="555" alt="root_zack___home_rpiadmin" src="https://github.com/parvez/network_scanner/assets/126749/3a2d0146-a4cc-4c66-a095-61b8aaad05f7">

**Comment by yff77** [comment]
Thank you very much, that works!

**Comment by ggonmar** [comment]
Hi, I am trying to follow the hint posted, but I have some doubts:
should I remove the network scanner integration from the UI and then add it on the configuration.yaml?

**Comment by steenderen** [comment]
@parvez please do not remove the custom data. I think it really useful for giving your own name to a device. The vendor naming can sometimes be pretty cryptic.

Do you think it's possible to add a routine to reload the mapping from configuration.yaml every now and then, so removing and re-adding is not necessary anymore?
