### ISSUE TITLE
Hosts names not showing

### ISSUE THREAD

**Issue by Vince1024** [parvez/network_scanner#4]
Hi,

Nice work, I love this feature !

Did I miss something cause I not able to get the Host Name of any of the devices detected by the scanner ?

Thanks.

![image](https://github.com/parvez/network_scanner/assets/81962401/08ccfb29-9586-4e5f-bb1a-f44c3bffb9ae)

**Comment by parvez** [comment]
thanks! hostnames are provided by nmap through your dns server. you might need to check if your dns server supports it.

https://askubuntu.com/questions/1363154/nmap-is-not-showing-hostnames

**Comment by Hubszo** [comment]
Same issue. Unfortunately, the provided article wasn't very helpful. My hostnames are populated in the local network, so why network scanner can pull this information?

**Comment by parvez** [comment]
it might be network specific issue, like firewall.
