### ISSUE TITLE
Column width

### ISSUE THREAD

**Issue by geotibi** [parvez/network_scanner#5]
Hello,

Is it any option to set the column width in the table? Right now I have 5 columns qhich are having same width even if some of them are having less chars.

**Comment by parvez** [comment]
you would need to look into https://github.com/custom-cards/flex-table-card for any further customizations.

**Comment by dxmnkd316** [comment]
You can also try just using straight up html tables in the markdown card like this:

```
## Devices
<table border="1" width="800"><tr><th>IP Address</th>
<th style="width:70%">Custom Name</th>
<th>Custom Description</th>
<th>Hostname</th>
<th>Vendor</th></tr>
{% for device in state_attr('sensor.network_scanner', 'devices') %} <tr>
  <td>{{ device.ip }}</td>
  <td>{{ device.name }}</td>
  <td>{{ device.type }}</td>
  <td>{{ device.hostname }}</td>
  <td>{{ device.vendor }}</td>
  </tr>
{% endfor %}
</tr></table>
```

If your dashboard is configured for sections, make sure you have the proper width set in the layout tab for the card.
