### ISSUE TITLE
Unable to scan other subnets

### ISSUE THREAD

**Issue by jjarboe01** [parvez/network_scanner#6]
I came across your integration and immediately set it up.  Works GREAT for scanning the local subnet that HomeAssistant runs in.  

My primary use case for this is to set a binary sensor for when people are connected to my guest wifi, to disable certain automations (like setting the security system to ARM if the people who live in the house all leave).  

I am not seeing any errors in the logs, and I have confirmed that HomeAssistant has full access through the firewall to the other subnets in my network.  Is this a limitation of the integration or Home Assistant in general?  I am running HA as an ESX OVA install currently, latest version as of 2/11/2024.

**Comment by giustanca** [comment]
Same problem here. No device in my "Guest" network. Able to scan device only in the principal network "Home".
Solutions?

**Comment by parvez** [comment]
since we are using `nmap`, you can provide multiple ip-range, separated by comma: `192.168.1.0/24,192.168.2.0/24`
