### ISSUE TITLE
Edit network Config ?

### ISSUE THREAD

**Issue by IanAdd** [parvez/network_scanner#7]
Hi, is there a way to edit the config rather than delete and recreate when I want to add a specific description to a MAC ?

**Comment by Trevsweb** [comment]
I would also like this. maybe a way of manually adding individual items after initial setup?

**Comment by Trevsweb** [comment]
I found that if you install a file browser on your home assistant you can navigate to homeassistant>.storage>core.config_entries

search for the network_mapper entry and then you can add/edit the maps. but remember the loop only looks for 25

**Comment by luispadarotto** [comment]
I was looking for the same thing, have anyone found a way to do it? Thanks!

**Comment by lucky81** [comment]
To workaround this I edited the code on line 21 to hardcode my device list. It would be even better to read these in from a separate file, but for now this works for me.

self.mac_mapping = self.parse_mac_mapping("""
FF:FF:FF:FF:FF:01;Nest WiFi;\n
FF:FF:FF:FF:FF:02;Upstairs Nest Protect;\n
""")

**Comment by lucazade** [comment]
> To workaround this I edited the code on line 21 to hardcode my device list. It would be even better to read these in from a separate file, but for now this works for me.
> 
> self.mac_mapping = self.parse_mac_mapping(""" FF:FF:FF:FF:FF:01;Nest WiFi;\n FF:FF:FF:FF:FF:02;Upstairs Nest Protect;\n """)

I edited "/homeassistant/custom_components/network_scanner/sensor.py",
added my personal MAC mappings as you suggested and restarted the component but 
I don't get any of the personal mappings in the scan itself. Any ideas?

**Comment by lucazade** [comment]
> > To workaround this I edited the code on line 21 to hardcode my device list. It would be even better to read these in from a separate file, but for now this works for me.
> > self.mac_mapping = self.parse_mac_mapping(""" FF:FF:FF:FF:FF:01;Nest WiFi;\n FF:FF:FF:FF:FF:02;Upstairs Nest Protect;\n """)
> 
> I edited "/homeassistant/custom_components/network_scanner/sensor.py", added my personal MAC mappings as you suggested and restarted the component but I don't get any of the personal mappings in the scan itself. Any ideas?

OK I got it!
I needed to restart also HA :)

**Comment by HAPSagan** [comment]
I have tried adding two of my devices as you suggested and then restarted but it doesn't work for me. Do you have any theories on what I might have done wrong? /Peter

**Comment by lucky81** [comment]
> I have tried adding two of my devices as you suggested and then restarted but it doesn't work for me. Do you have any theories on what I might have done wrong? /Peter
> 
> (""" 00:1e:06:42:93:9b;HomeAssistant;Odroid;\n a4:e5:7c:a7:24:da;Plug Odroid Shelly;Shelly/Espressif;\n """)

Try removing the last semicolons before the newline character.

**Comment by HAPSagan** [comment]
I have now tried all three examples below, but so far no success. /Peter

        self.mac_mapping = self.parse_mac_mapping(""" A8:42:A1:3E:64:C4;Router;TP-Link Limited;\n """)
        self.mac_mapping = self.parse_mac_mapping(""" A8:42:A1:3E:64:C4;Router;TP-Link Limited\n """)
        self.mac_mapping = self.parse_mac_mapping(""" A8:42:A1:3E:64:C4;Router;TP-Link Limited """)

**Comment by lucazade** [comment]
> I have now tried all three examples below, but so far no success. /Peter
> 
> ```
>     self.mac_mapping = self.parse_mac_mapping(""" A8:42:A1:3E:64:C4;Router;TP-Link Limited;\n """)
>     self.mac_mapping = self.parse_mac_mapping(""" A8:42:A1:3E:64:C4;Router;TP-Link Limited\n """)
>     self.mac_mapping = self.parse_mac_mapping(""" A8:42:A1:3E:64:C4;Router;TP-Link Limited """)
> ```

try the following:
self.mac_mapping = self.parse_mac_mapping("A8:42:A1:3E:64:C4;Router;TP-Link Limited")
and check for errors in logs

**Comment by HAPSagan** [comment]
That worked! Thank you. Can you tell me how to add another device?
For example: 96.8A.4A.CB.AD.1E;Range Extender;TP-Link Limited

**Comment by parvez** [comment]
I have updated to support unlimited devices through configuration.yaml
