### ISSUE TITLE
Error - Config flow could not be loaded: Unknown error

### ISSUE THREAD

**Issue by kebabfotografen** [parvez/network_scanner#8]
Hi!

I'm getting the above error when trying to add the custom integration. I have not made any edits to the config_flow.py file, any ideas?

![image](https://github.com/parvez/network_scanner/assets/84571917/2bf1aeef-21a1-4177-adc2-5979061563ad)
![image](https://github.com/parvez/network_scanner/assets/84571917/ce25d1c7-628e-4397-8ef1-be867eee27d2)

**Comment by parvez** [comment]
try the updated version. The old and new one both work for me.
