### ISSUE TITLE
Trying to edit Custom Names and descriptions on large number of devices

### ISSUE THREAD

**Issue by ggonmar** [parvez/network_scanner#9]
Hi,

I am trying to customize my list of devices returned from the integration of network_scanner with the hints shown on other issues and documentation.
I have managed to get _some_ of the devices to show the custom name assigned from the configuration.yaml:
![image](https://github.com/parvez/network_scanner/assets/11583288/fb27ef9d-817d-413e-898e-b395395d117d)

However, since I have more than 25 devices in place, the devices beyond the 25th one dont seem to have picked up the custom name and description I intended for them:
![image](https://github.com/parvez/network_scanner/assets/11583288/c637cf07-e763-4bca-be50-4173849285dd)

When I go to the integration and click on the "Add entry", I see that there have been listed only the first 25 elements that I added on the configuration.yaml, but nothing beyond.

If it is not an issue on the integration, and it is actually me not being able to sort things out, could I get some assistance on how to proceed??

Thank you!

**Comment by yff77** [comment]
If I remember correctly, the custom list is limited to 25 entries.

(your configuration seems correct btw: the network scanner integrations stays in the UI and at the same time, you add in the configuration the lines in which you define de mac-addresses)

**Comment by ggonmar** [comment]
is there a way I can modify that limit of 25 ?

**Comment by lucky81** [comment]
The limit of 25 is only in the popup screen, not in the actual code the applies the rules. To workaround this I edited the code on line 21 to hardcode my device list without limitation.

`
self.mac_mapping = self.parse_mac_mapping("""
FF:FF:FF:FF:FF:01;Nest WiFi;\n
FF:FF:FF:FF:FF:02;Upstairs Nest Protect;\n
""")
`

**Comment by parvez** [comment]
I have updated to support unlimited devices through configuration.yaml
